[project]
site_name = "Cheatsheets"
site_description = "A collection of personal cheatsheets."
site_author = "Nicholas Wilde"
site_url = "https://nicholaswilde.io/cheatsheets"
copyright = "Copyright &copy; 2026 Nicholas Wilde"
dev_addr = "0.0.0.0:8000"
repo_url = "https://github.com/nicholaswilde/cheatsheets"
repo_name = "nicholaswilde/cheatsheets"
edit_uri = "edit/main/docs/"
plugins = [
  { tags = { tags_file = "tags.md" } },
  "search",
  { minify = { minify_html = true } },
]
extra_css = [
  "css/neoteroi-mkdocs.css",
  "stylesheets/extra.css",
]
extra_javascript = [
  "javascripts/mathjax.js",
  "https://polyfill.io/v3/polyfill.min.js?features=es6",
  "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js", 
]

[[project.nav]]
Home = "index.md"

[[project.nav]]
Cheatsheets = [
  { age = "age.md" },
  { agy = "agy.md" },
  { ansible = "ansible.md" },
  { "ansible-pull" = "ansible-pull.md" },
  { awk = "awk.md" },
  { bash = "bash.md" },
  { bat = "bat.md" },
  { brew = "brew.md" },
  { bun = "bun.md" },
  { bw = "bw.md" },
  { cargo = "cargo.md" },
  { column = "column.md" },
  { crontab = "crontab.md" },
  { cross = "cross.md" },
  { curl = "curl.md" },
  { cut = "cut.md" },
  { docker = "docker.md" },
  { eget = "eget.md" },
  { fd = "fd.md" },
  { find = "find.md" },
  { fzf = "fzf.md" },
  { gh = "gh.md" },
  { git = "git.md" },
  { gpg = "gpg.md" },
  { "gpg-agent" = "gpg-agent.md" },
  { grep = "grep.md" },
  { journalctl = "journalctl.md" },
  { jq = "jq.md" },
  { lpass = "lpass.md" },
  { lxc = "lxc.md" },
  { lychee = "lychee.md" },
  { mise = "mise.md" },
  { nfs = "nfs.md" },
  { openssl = "openssl.md" },
  { pass = "pass.md" },
  { proxmox = "proxmox.md" },
  { ps = "ps.md" },
  { regex = "regex.md" },
  { reprepro = "reprepro.md" },
  { restic = "restic.md" },
  { "restic-age-key" = "restic-age-key.md" },
  { rg = "rg.md" },
  { rpi = "rpi.md" },
  { rumdl = "rumdl.md" },
  { sed = "sed.md" },
  { shuck = "shuck.md" },
  { sops = "sops.md" },
  { ssh = "ssh.md" },
  { "ssh-agent" = "ssh-agent.md" },
  { "ssh-keygen" = "ssh-keygen.md" },
  { syncthing = "syncthing.md" },
  { systemctl = "systemctl.md" },
  { "systemd-timer" = "systemd-timer.md" },
  { tar = "tar.md" },
  { task = "task.md" },
  { timedatectl = "timedatectl.md" },
  { tmux = "tmux.md" },
  { traefik = "traefik.md" },
  { typos = "typos.md" },
  { uv = "uv.md" },
  { wsl = "wsl.md" },
  { xz = "xz.md" },
  { yq = "yq.md" },
  { yubikey = "yubikey.md" },
  { zensical = "zensical.md" }
]

[[project.nav]]
Reference = [
  { development = "reference/development.md" }
]

[project.extra]
social = [
    { icon = "fontawesome/solid/house", link = "https://nicholaswilde.io/" },
    { icon = "fontawesome/brands/github", link = "https://github.com/nicholaswilde" },
    { icon = "fontawesome/brands/twitter", link = "https://twitter.com/nicholascwilde" },
    { icon = "fontawesome/brands/instagram", link = "https://www.instagram.com/wildewoodworking/" },
    { icon = "fontawesome/brands/linkedin-in", link = "https://www.linkedin.com/in/nicholaswilde" },
    { icon = "fontawesome/brands/facebook", link = "https://www.facebook.com/nicholas.wilde/" },
    { icon = "fontawesome/brands/keybase", link = "https://keybase.io/nicholaswilde" },
    { icon = "fontawesome/solid/key", link = "https://github.com/nicholaswilde.gpg" },
]

[project.theme]
name = "material"
features = [
    "navigation.footer",
    "content.action.edit",
    "content.action.view"
]

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[markdown]
extensions = [
    "neoteroi.timeline",
    "footnotes",
    "attr_list",
    "md_in_html",
    "admonition",
    "tables",
    { "pymdownx.arithmatex" = { generic = true } },
    { "pymdownx.emoji" = { emoji_index = "pymdownx.emoji.twemoji", emoji_generator = "pymdownx.emoji.to_svg" } },
    { "pymdownx.highlight" = { anchor_linenums = true } },
    "pymdownx.inlinehilite",
    "pymdownx.snippets",
    { "pymdownx.superfences" = { custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
] } },
    { "pymdownx.tabbed" = { alternate_style = true } },
    { "pymdownx.magiclink" = { repo_url_shorthand = true, user = "nicholaswilde", repo = "cheatsheets" } },
]
